name: book_sharing_system
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  requests: ^3.0.3
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  smooth_star_rating: ^1.0.4+2
  carousel_slider: ^1.4.1
  flutter_image_compress: ^0.6.5+1
  flutter_spinkit: "^4.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
